import type { Activity, Meal } from '../types';
import { accent } from './colors';
import { addDays, getTodayISO } from '../utils/date';

export const todaySeedDate = getTodayISO();
export const initialMeals: Meal[] = [
  {
    id: 'fried-chicken-bowl',
    name: 'Fried Chicken Bowl',
    date: todaySeedDate,
    time: '22:10',
    calories: 988,
    protein: 54,
    carbs: 39,
    fat: 60,
    source: 'manual',
    category: 'Dinner',
  },
  {
    id: 'greek-yogurt',
    name: 'Greek Yogurt',
    date: todaySeedDate,
    time: '08:20',
    calories: 240,
    protein: 22,
    carbs: 18,
    fat: 7,
    source: 'manual',
    category: 'Breakfast',
  },
  {
    id: 'chicken-wrap',
    name: 'Chicken Wrap',
    date: addDays(todaySeedDate, -1),
    time: '13:15',
    calories: 620,
    protein: 42,
    carbs: 58,
    fat: 24,
    source: 'manual',
    category: 'Lunch',
  },
  {
    id: 'protein-oats',
    name: 'Protein Oats',
    date: addDays(todaySeedDate, -2),
    time: '07:45',
    calories: 430,
    protein: 31,
    carbs: 52,
    fat: 12,
    source: 'manual',
    category: 'Breakfast',
  },
];
export const initialActivities: Activity[] = [
  {
    id: 'design-review',
    title: 'Design Review',
    description:
      'Review the onboarding screens and finalize the spacing, typography, and interaction details for the next build.',
    date: todaySeedDate,
    startDate: todaySeedDate,
    endDate: todaySeedDate,
    startTime: '09:00',
    endTime: '10:30',
    category: 'Productivity',
    color: accent,
    allDay: false,
    repeat: 'none',
  },
  {
    id: 'focus-time',
    title: 'Focus Time',
    description: 'Protected focus block for priority product work, planning, and careful follow-through.',
    date: todaySeedDate,
    startDate: todaySeedDate,
    endDate: todaySeedDate,
    startTime: '13:00',
    endTime: '15:00',
    category: 'Productivity',
    color: '#716dff',
    allDay: false,
    repeat: 'none',
  },
  {
    id: 'workout-session',
    title: 'Workout Session',
    description:
      'Strength training and light cardio. Focus on consistency and keep the session balanced and efficient.',
    date: addDays(todaySeedDate, 1),
    startDate: addDays(todaySeedDate, 1),
    endDate: addDays(todaySeedDate, 1),
    startTime: '17:30',
    endTime: '18:30',
    category: 'Health',
    color: '#5d8cff',
    allDay: false,
    repeat: 'none',
  },
  {
    id: 'deep-work',
    title: 'Deep Work',
    description: 'A quiet work session for solving the hardest open task without context switching.',
    date: addDays(todaySeedDate, 2),
    startDate: addDays(todaySeedDate, 2),
    endDate: addDays(todaySeedDate, 2),
    startTime: '10:00',
    endTime: '12:00',
    category: 'Productivity',
    color: '#ffa43b',
    allDay: false,
    repeat: 'none',
  },
];
