import { StyleSheet } from 'react-native';
import { accent, carbsColor, fatColor } from '../constants/colors';
import {
  CARD_HEIGHT,
  NUTRITION_DATE_CARD_WIDTH,
  NUTRITION_FIXED_HEADER_HEIGHT,
  TIMELINE_VIEWPORT_HEIGHT,
  TIMELINE_WIDTH,
} from '../constants/layout';

const TAB_QR_BUTTON_SIZE = 64;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    alignItems: 'center',
  },
  phoneFrame: {
    flex: 1,
    width: '100%',
    maxWidth: 430,
    overflow: 'hidden',
  },
  homeContent: {
    flex: 1,
    paddingHorizontal: 27,
    paddingTop: 68,
    paddingBottom: 122,
  },
  screenHeaderRow: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 10,
    elevation: 10,
  },
  screenHeaderActions: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 10,
    zIndex: 11,
    elevation: 11,
  },
  homeHeader: {
  },
  homeTitleBlock: {
    flex: 1,
    paddingRight: 12,
  },
  homePageTitle: {
    fontSize: 30,
    fontWeight: '700',
    lineHeight: 38,
    letterSpacing: 0,
    opacity: 0.46,
  },
  homeHeaderActions: {
  },
  themeButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  homeActionButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    zIndex: 12,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 7,
  },
  homeActionButtonPressed: {
    opacity: 0.72,
    transform: [{ scale: 0.96 }],
  },
  aiCoachModalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  aiCoachSheet: {
    width: '100%',
    maxWidth: 430,
    height: '90%',
    borderTopLeftRadius: 34,
    borderTopRightRadius: 34,
    borderWidth: 1,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 18,
    shadowColor: accent,
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.18,
    shadowRadius: 28,
    elevation: 22,
  },
  aiCoachHandle: {
    width: 46,
    height: 4,
    alignSelf: 'center',
    borderRadius: 3,
    opacity: 0.8,
  },
  aiCoachHeader: {
    minHeight: 66,
    marginTop: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  aiCoachTitleRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: 14,
  },
  aiCoachLogo: {
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(184,239,47,0.26)',
    backgroundColor: 'rgba(184,239,47,0.08)',
    shadowColor: accent,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.28,
    shadowRadius: 18,
    elevation: 9,
  },
  aiCoachTitleBlock: {
    flex: 1,
    marginLeft: 13,
  },
  aiCoachTitle: {
    color: '#f6f8f0',
    fontSize: 25,
    lineHeight: 31,
    fontWeight: '800',
  },
  aiCoachSubtitle: {
    marginTop: 3,
    color: 'rgba(246,248,240,0.58)',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  aiCoachCloseButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    backgroundColor: 'rgba(255,255,255,0.07)',
  },
  aiCoachConversation: {
    flex: 1,
    paddingTop: 22,
  },
  aiCoachMessageRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  aiCoachAvatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(184,239,47,0.2)',
    backgroundColor: 'rgba(184,239,47,0.08)',
    shadowColor: accent,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 6,
  },
  aiCoachBubble: {
    flex: 1,
    minHeight: 54,
    marginLeft: 10,
    borderRadius: 21,
    borderTopLeftRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    backgroundColor: 'rgba(255,255,255,0.07)',
    paddingHorizontal: 15,
    paddingVertical: 13,
  },
  aiCoachBubbleText: {
    color: '#f6f8f0',
    fontSize: 15,
    lineHeight: 21,
    fontWeight: '700',
  },
  aiCoachChipRow: {
    marginTop: 22,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  aiCoachUserMessage: {
    alignSelf: 'flex-end',
    maxWidth: '84%',
    marginTop: 14,
    borderRadius: 20,
    borderBottomRightRadius: 8,
    backgroundColor: accent,
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  aiCoachUserMessageText: {
    color: '#151713',
    fontSize: 14,
    lineHeight: 19,
    fontWeight: '800',
  },
  aiCoachPromptChip: {
    minHeight: 36,
    marginRight: 9,
    marginBottom: 9,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(184,239,47,0.18)',
    backgroundColor: 'rgba(255,255,255,0.06)',
    paddingHorizontal: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  aiCoachPromptChipText: {
    color: 'rgba(246,248,240,0.76)',
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '800',
  },
  aiCoachInputDock: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 14,
  },
  aiCoachInputBox: {
    flex: 1,
    minHeight: 52,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    backgroundColor: 'rgba(255,255,255,0.08)',
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 16,
    paddingRight: 6,
  },
  aiCoachInput: {
    flex: 1,
    minHeight: 48,
    color: '#f6f8f0',
    fontSize: 14,
    fontWeight: '700',
    paddingVertical: 0,
  },
  aiCoachSendButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: accent,
    shadowColor: accent,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.22,
    shadowRadius: 12,
    elevation: 6,
  },
  aiCoachMicButton: {
    width: 52,
    height: 52,
    marginLeft: 9,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(184,239,47,0.2)',
    backgroundColor: 'rgba(255,255,255,0.07)',
  },
  topActionButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: accent,
    shadowColor: accent,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.28,
    shadowRadius: 18,
    elevation: 8,
  },
  topActionNeutralButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activityCards: {
    flex: 1,
    marginTop: 24,
    marginHorizontal: -4,
  },
  activityCardsContent: {
    gap: 10,
    paddingHorizontal: 4,
    paddingBottom: 16,
    justifyContent: 'flex-start',
    flexGrow: 1,
  },
  homeEmptyActivityCard: {
    minHeight: 94,
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingVertical: 16,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  activityTouchable: {
    borderRadius: 24,
  },
  homeActivityCard: {
    minHeight: 100,
    borderRadius: 24,
    paddingLeft: 24,
    paddingRight: 18,
    paddingVertical: 17,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'flex-start',
    overflow: 'hidden',
    shadowOffset: { width: 0, height: 14 },
    shadowRadius: 22,
    elevation: 9,
  },
  activityGlassSheen: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 30,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    opacity: 0.62,
  },
  activityEdgeGlow: {
    position: 'absolute',
    left: 0,
    top: 15,
    bottom: 15,
    width: 13,
    borderTopRightRadius: 14,
    borderBottomRightRadius: 14,
  },
  activityEdgeFade: {
    position: 'absolute',
    left: 0,
    top: 10,
    bottom: 10,
    width: 82,
  },
  activityTextBlock: {
    flex: 1,
    marginLeft: 0,
    paddingRight: 4,
  },
  activityCardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  activityTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 22,
  },
  activityTime: {
    flexShrink: 0,
    maxWidth: 126,
    textAlign: 'right',
    fontSize: 15,
    lineHeight: 20,
  },
  activityDescription: {
    marginTop: 9,
    fontSize: 13,
    lineHeight: 18,
  },
  activityAccent: {
    position: 'absolute',
    left: 0,
    top: 21,
    bottom: 21,
    width: 4,
    borderTopRightRadius: 4,
    borderBottomRightRadius: 4,
    opacity: 0.9,
  },
  statsCard: {
    minHeight: 222,
    marginTop: 18,
    marginBottom: 24,
    borderRadius: 23,
    paddingHorizontal: 20,
    paddingTop: 19,
    paddingBottom: 20,
    borderWidth: 1,
    shadowOffset: { width: 0, height: 18 },
    shadowRadius: 28,
    elevation: 14,
  },
  statsTitle: {
    marginBottom: 19,
    color: accent,
    fontSize: 19,
    fontWeight: '700',
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  statItem: {
    width: '50%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  statLeft: {
    paddingRight: 19,
    borderRightWidth: 1,
  },
  statRight: {
    paddingLeft: 21,
  },
  statTop: {
    marginBottom: 28,
  },
  statIconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statTextWrap: {
    flex: 1,
    marginLeft: 14,
  },
  statLabel: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    lineHeight: 14,
  },
  statValueRow: {
    marginTop: 6,
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  statValue: {
    fontSize: 24,
    fontWeight: '500',
    lineHeight: 29,
  },
  statUnit: {
    marginLeft: 4,
    marginBottom: 3,
    fontSize: 13,
    lineHeight: 17,
  },
  statTrack: {
    height: 4,
    marginTop: 7,
    borderRadius: 4,
    overflow: 'visible',
  },
  statFill: {
    height: '100%',
    borderRadius: 3,
    backgroundColor: accent,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 15,
    elevation: 10,
  },
  calendarContent: {
    flex: 1,
    paddingTop: 68,
    paddingHorizontal: 27,
    paddingBottom: 130,
  },
  calendarTop: {
    position: 'relative',
  },
  monthRow: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: 178,
    height: 44,
    justifyContent: 'center',
    flexShrink: 0,
  },
  monthTitle: {
    width: '100%',
    textAlign: 'left',
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 26,
    letterSpacing: 0,
    opacity: 0.82,
  },
  calendarActions: {
    position: 'absolute',
    top: 0,
    right: 54,
  },
  calendarHeaderAddButton: {
    position: 'absolute',
    top: 0,
    right: 0,
  },
  todayButton: {
    height: 36,
    paddingHorizontal: 12,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  todayButtonText: {
    fontSize: 12,
    fontWeight: '800',
  },
  filterButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  weekHeader: {
    marginTop: 36,
    flexDirection: 'row',
  },
  weekday: {
    flex: 1,
    textAlign: 'center',
    fontSize: 12,
    fontWeight: '700',
  },
  calendarGrid: {
    marginTop: 24,
  },
  calendarSwipeZone: {
    width: '100%',
  },
  weekModeRow: {
    marginTop: 17,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 7,
  },
  weekDayCard: {
    flex: 1,
    height: 70,
    borderRadius: 18,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 5,
  },
  weekDayLabel: {
    fontSize: 10,
    fontWeight: '600',
    lineHeight: 13,
  },
  weekDayNumber: {
    marginTop: 4,
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 22,
  },
  weekDotRow: {
    height: 6,
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
  },
  weekActivityDot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
  },
  weekTimelinePanel: {
    marginTop: 18,
    height: TIMELINE_VIEWPORT_HEIGHT,
    borderRadius: 27,
    borderWidth: 1,
    paddingTop: 16,
    paddingBottom: 10,
    paddingHorizontal: 0,
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.18,
    shadowRadius: 28,
    elevation: 10,
    overflow: 'hidden',
  },
  timelineVerticalScroll: {
    flex: 1,
  },
  timelineVerticalContent: {
    paddingBottom: 18,
  },
  weekAllDaySection: {
    paddingHorizontal: 18,
    gap: 10,
    marginBottom: 10,
  },
  allDayTimelineCard: {
    minHeight: 58,
    borderRadius: 18,
    borderWidth: 1,
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'center',
  },
  allDayTimelineText: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  timelineScroll: {
    width: '100%',
  },
  timelineScrollContent: {
    paddingHorizontal: 16,
    flexGrow: 0,
  },
  timelineContent: {
    position: 'relative',
    flexGrow: 0,
    flexShrink: 0,
  },
  timelineHourRow: {
    height: 32,
    position: 'relative',
  },
  timelineHourMarker: {
    position: 'absolute',
    top: 0,
  },
  timelineHourText: {
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 17,
  },
  timelineGridWrap: {
    marginTop: 6,
    position: 'relative',
    width: TIMELINE_WIDTH,
  },
  timelineGuideLine: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 1,
    borderLeftWidth: 1,
    borderStyle: 'dotted',
    borderLeftColor: 'rgba(148,148,148,0.19)',
  },
  timelineActivityCard: {
    position: 'absolute',
    height: CARD_HEIGHT,
    borderRadius: 18,
    borderWidth: 1,
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'stretch',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 18,
    elevation: 6,
  },
  timelineCardAccent: {
    width: 4,
    borderTopRightRadius: 5,
    borderBottomRightRadius: 5,
  },
  timelineCardText: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  timelineCardTitle: {
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 18,
  },
  timelineCardMeta: {
    marginTop: 3,
    fontSize: 11,
    lineHeight: 15,
  },
  weekEmptyState: {
    minHeight: 440,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  weekZoomResetButton: {
    position: 'absolute',
    right: 16,
    bottom: 16,
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  weekEmptyText: {
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'center',
  },
  calendarWeek: {
    height: 64,
    flexDirection: 'row',
  },
  dayCell: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  datePill: {
    width: 45,
    height: 43,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dateActivityDot: {
    position: 'absolute',
    bottom: 5,
    width: 5,
    height: 5,
    borderRadius: 2.5,
  },
  datePillSelected: {
    backgroundColor: accent,
  },
  todayDatePill: {
    borderWidth: 1,
    borderColor: 'rgba(184,239,47,0.58)',
    backgroundColor: 'rgba(184,239,47,0.07)',
  },
  dateText: {
    fontSize: 17,
    fontWeight: '500',
  },
  selectedDate: {
    color: '#101010',
    fontWeight: '700',
  },
  weekendDate: {
    color: '#c66f6f',
  },
  eventsPanel: {
    marginHorizontal: -28,
    marginTop: 5,
    borderTopWidth: 1,
    flex: 1,
  },
  eventsPanelContent: {
    paddingHorizontal: 28,
    paddingTop: 25,
    paddingBottom: 138,
  },
  todayTitle: {
    marginBottom: 18,
    color: '#8bd314',
    fontSize: 17,
    fontWeight: '600',
  },
  eventRow: {
    minHeight: 74,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  eventDot: {
    width: 10,
    height: 10,
    marginTop: 11,
    borderRadius: 5,
  },
  eventTime: {
    width: 104,
    marginLeft: 18,
    fontSize: 16,
    lineHeight: 30,
  },
  eventDetails: {
    flex: 1,
    minHeight: 56,
    paddingBottom: 16,
  },
  eventDivider: {
    borderBottomWidth: 1,
  },
  eventTitle: {
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 23,
  },
  eventMeta: {
    fontSize: 15,
    lineHeight: 20,
  },
  emptyActivitiesText: {
    fontSize: 16,
    lineHeight: 22,
  },
  emptyAgendaCard: {
    minHeight: 78,
    borderRadius: 22,
    paddingHorizontal: 18,
    paddingVertical: 16,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  emptyAgendaIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyAgendaTextBlock: {
    flex: 1,
    marginLeft: 14,
  },
  emptyAgendaTitle: {
    fontSize: 17,
    fontWeight: '700',
    lineHeight: 22,
  },
  nutritionContent: {
    flex: 1,
  },
  nutritionFixedHeader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 20,
    elevation: 20,
    paddingHorizontal: 27,
    paddingTop: 68,
    paddingBottom: 34,
  },
  nutritionBodyScroll: {
    flex: 1,
  },
  nutritionBodyContent: {
    paddingHorizontal: 27,
    paddingTop: NUTRITION_FIXED_HEADER_HEIGHT,
    paddingBottom: 172,
  },
  nutritionHeader: {
  },
  nutritionTitle: {
    flex: 1,
    fontSize: 32,
    fontWeight: '700',
    lineHeight: 40,
    opacity: 0.84,
  },
  nutritionHeaderActions: {
  },
  nutritionDateHeader: {
    marginTop: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  nutritionMonthLabel: {
    width: 132,
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 25,
    opacity: 0.76,
  },
  streakPill: {
    height: 40,
    paddingHorizontal: 13,
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 6,
  },
  streakText: {
    fontSize: 13,
    fontWeight: '600',
    opacity: 0.78,
  },
  nutritionWeekRow: {
    paddingHorizontal: 1,
    paddingRight: 24,
    paddingVertical: 6,
    flexDirection: 'row',
    gap: 7,
  },
  nutritionDateScrollerFrame: {
    height: 88,
    marginTop: 14,
    marginHorizontal: -1,
    marginBottom: 20,
    overflow: 'visible',
  },
  nutritionWeekScroll: {
    height: 88,
    flexGrow: 0,
    overflow: 'visible',
  },
  nutritionDateCard: {
    width: NUTRITION_DATE_CARD_WIDTH,
    height: 70,
    flexGrow: 0,
    flexShrink: 0,
    borderRadius: 18,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 5,
  },
  caloriesCard: {
    minHeight: 150,
    marginTop: 0,
    borderRadius: 28,
    paddingLeft: 26,
    paddingRight: 48,
    borderWidth: 1,
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.1,
    shadowRadius: 24,
    elevation: 12,
  },
  caloriesLeftNumber: {
    fontSize: 46,
    fontWeight: '700',
    lineHeight: 54,
    opacity: 0.86,
  },
  caloriesLeftLabel: {
    marginTop: 4,
    fontSize: 17,
    lineHeight: 22,
    opacity: 0.82,
  },
  calorieMetaBox: {
    alignSelf: 'flex-start',
    marginTop: 9,
    marginLeft: -7,
    minHeight: 22,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 6,
    paddingVertical: 3,
    flexDirection: 'row',
    alignItems: 'center',
    opacity: 0.7,
  },
  calorieMetaItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  calorieMetaDivider: {
    width: 1,
    height: 12,
    marginHorizontal: 6,
    borderRadius: 1,
  },
  calorieMetaText: {
    marginLeft: 3,
    fontSize: 8,
    fontWeight: '700',
    opacity: 0.72,
  },
  calorieMetaStrong: {
    fontWeight: '800',
  },
  caloriesStatusPill: {
    position: 'absolute',
    top: 18,
    right: 14,
    width: 7,
    height: 28,
    borderRadius: 4,
    opacity: 0.82,
  },
  caloriesRingWrap: {
    position: 'relative',
    width: 108,
    height: 108,
    marginLeft: 0,
    marginRight: 2,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  nutritionRing: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  nutritionRingTrack: {
    position: 'absolute',
  },
  nutritionRingHalfClip: {
    position: 'absolute',
    top: 0,
    overflow: 'hidden',
  },
  nutritionRingArc: {
    position: 'absolute',
  },
  nutritionRingCenter: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  fatGlyph: {
    position: 'relative',
  },
  fatBubble: {
    position: 'absolute',
    opacity: 0.92,
    shadowColor: fatColor,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.22,
    shadowRadius: 6,
  },
  carbsGlyph: {
    position: 'relative',
    alignItems: 'center',
  },
  carbsStem: {
    position: 'absolute',
    top: '12%',
    bottom: '8%',
    width: 2,
    borderRadius: 2,
  },
  grainLeft: {
    position: 'absolute',
    left: '16%',
    width: '34%',
    height: '20%',
    borderTopLeftRadius: 12,
    borderBottomRightRadius: 12,
    transform: [{ rotate: '-32deg' }],
    shadowColor: carbsColor,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 5,
  },
  grainRight: {
    position: 'absolute',
    right: '16%',
    width: '34%',
    height: '20%',
    borderTopRightRadius: 12,
    borderBottomLeftRadius: 12,
    transform: [{ rotate: '32deg' }],
    shadowColor: carbsColor,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 5,
  },
  macroGrid: {
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  macroCard: {
    flex: 1,
    height: 169,
    minWidth: 0,
    borderRadius: 24,
    padding: 12,
    borderWidth: 1,
    position: 'relative',
    overflow: 'hidden',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 8,
  },
  macroCardSpacing: {
    marginRight: 10,
  },
  macroValueRow: {
    minHeight: 25,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  macroValue: {
    flexShrink: 1,
    fontSize: 21,
    fontWeight: '700',
    lineHeight: 26,
    opacity: 0.86,
  },
  macroStatusPill: {
    width: 6,
    height: 22,
    marginLeft: 6,
    borderRadius: 4,
    flexShrink: 0,
    opacity: 0.82,
  },
  macroLabel: {
    marginTop: 3,
    marginBottom: 7,
    fontSize: 12,
    lineHeight: 16,
    opacity: 0.82,
  },
  macroRingSlot: {
    width: '100%',
    height: 76,
    alignItems: 'center',
    justifyContent: 'center',
  },
  goalPercentChip: {
    minHeight: 24,
    paddingHorizontal: 9,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  goalPercentChipText: {
    fontSize: 10,
    fontWeight: '700',
  },
  macroPercentChip: {
    position: 'absolute',
    right: 10,
    bottom: 10,
  },
  caloriesPercentChip: {
    position: 'absolute',
    right: -2,
    bottom: 2,
  },
  nutritionCarouselShell: {
    marginHorizontal: -27,
    overflow: 'hidden',
  },
  nutritionCarouselScroller: {
    width: '100%',
  },
  nutritionCarouselContent: {
    alignItems: 'stretch',
  },
  nutritionCarouselPage: {
    flexShrink: 0,
    flexGrow: 0,
  },
  nutritionCarouselPageInner: {
    width: '100%',
    paddingHorizontal: 39,
  },
  nutritionInsightCard: {
    height: 339,
    borderRadius: 28,
    borderWidth: 1,
    paddingHorizontal: 22,
    paddingVertical: 22,
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.1,
    shadowRadius: 24,
    elevation: 12,
  },
  aiSummaryCard: {
    height: 339,
    borderRadius: 28,
    borderWidth: 1,
    paddingHorizontal: 22,
    paddingVertical: 22,
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.1,
    shadowRadius: 24,
    elevation: 12,
  },
  nutritionInsightTopRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  nutritionInsightIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  nutritionInsightTitle: {
    fontSize: 19,
    lineHeight: 24,
    fontWeight: '800',
  },
  nutritionInsightSubtitle: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
  },
  nutritionRatingChip: {
    minHeight: 28,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.22,
    shadowRadius: 14,
    elevation: 5,
  },
  nutritionRatingChipText: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '800',
  },
  nutritionRatingChipSpacer: {
    minWidth: 58,
    minHeight: 28,
  },
  foodBalanceBody: {
    marginTop: 18,
    flexDirection: 'row',
    alignItems: 'center',
  },
  compositionRingWrap: {
    width: 128,
    height: 128,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  compositionRingTrack: {
    width: 126,
    height: 126,
    borderRadius: 63,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    shadowColor: fatColor,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
    elevation: 6,
    zIndex: 1,
  },
  compositionRingCenter: {
    width: 62,
    height: 62,
    borderRadius: 31,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: accent,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 14,
    elevation: 5,
  },
  macroCompositionList: {
    flex: 1,
    marginLeft: 16,
  },
  macroCompositionRow: {
    minHeight: 22,
    flexDirection: 'row',
    alignItems: 'center',
  },
  macroCompositionRowSpacing: {
    marginBottom: 11,
  },
  macroCompositionDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 9,
  },
  macroCompositionLabel: {
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '800',
  },
  macroCompositionPercent: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '900',
  },
  aiSummaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  aiSummaryLogoRing: {
    width: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    overflow: 'visible',
    shadowColor: accent,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 14,
    elevation: 5,
  },
  aiSummaryLogoCore: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: accent,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.22,
    shadowRadius: 12,
    elevation: 6,
    position: 'relative',
    zIndex: 1,
  },
  aiSummaryTitleBlock: {
    flex: 1,
    marginLeft: 12,
    paddingRight: 10,
  },
  nutritionAiPlaceholder: {
    marginTop: 22,
    fontSize: 13,
    lineHeight: 20,
    fontWeight: '700',
  },
  nutritionSummaryDivider: {
    height: 1,
    marginTop: 20,
    borderRadius: 1,
  },
  nutritionTagRow: {
    marginTop: 19,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  nutritionTag: {
    minHeight: 28,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  nutritionTagText: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '800',
  },
  nutritionCarouselDots: {
    marginTop: 8,
    flexDirection: 'row',
    alignSelf: 'center',
    gap: 9,
  },
  nutritionCarouselDot: {
    width: 9,
    height: 9,
    borderRadius: 4.5,
  },
  recentTitle: {
    marginTop: 15,
    marginBottom: 9,
    fontSize: 21,
    fontWeight: '700',
    lineHeight: 28,
    opacity: 0.9,
  },
  mealCard: {
    minHeight: 118,
    borderRadius: 25,
    borderWidth: 1,
    padding: 17,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.09,
    shadowRadius: 20,
    elevation: 10,
  },
  mealCardStack: {
    marginTop: 9,
  },
  mealCardBody: {
    flex: 1,
  },
  mealCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  mealName: {
    flex: 1,
    fontSize: 17,
    fontWeight: '700',
    lineHeight: 22,
    opacity: 0.9,
  },
  mealTimePill: {
    minHeight: 30,
    paddingHorizontal: 10,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mealTimeText: {
    fontSize: 11,
    fontWeight: '600',
  },
  mealCaloriesRow: {
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  mealCaloriesText: {
    fontSize: 16,
    fontWeight: '700',
    opacity: 0.9,
  },
  mealMacrosRow: {
    marginTop: 15,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  mealMacroText: {
    fontSize: 13,
    fontWeight: '600',
  },
  mealMacroDivider: {
    width: 1,
    height: 18,
    marginHorizontal: 3,
  },
  nutritionEmptyCard: {
    minHeight: 92,
    borderRadius: 24,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  nutritionEmptyText: {
    fontSize: 15,
    fontWeight: '600',
  },
  profileContent: {
    flex: 1,
    paddingHorizontal: 27,
    paddingTop: 68,
  },
  profileHeader: {
  },
  profileTitle: {
    fontSize: 38,
    fontWeight: '800',
    lineHeight: 46,
  },
  profileAvatar: {
  },
  profileScroll: {
    flex: 1,
    marginHorizontal: -27,
  },
  profileScrollContent: {
    paddingHorizontal: 27,
    paddingTop: 18,
    paddingBottom: 140,
  },
  profileCard: {
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingVertical: 16,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    overflow: 'hidden',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 8,
  },
  profileName: {
    fontSize: 23,
    fontWeight: '800',
    lineHeight: 29,
  },
  profileMeta: {
    marginTop: 6,
    fontSize: 15,
    lineHeight: 21,
  },
  profileHeaderBadge: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileOptionStack: {
    marginTop: 14,
    gap: 12,
  },
  profileOptionCard: {
    minHeight: 70,
    borderRadius: 22,
    paddingLeft: 16,
    paddingRight: 14,
    paddingVertical: 12,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 7,
  },
  profileOptionIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 13,
  },
  profileOptionText: {
    flex: 1,
    paddingRight: 10,
  },
  profileOptionTitle: {
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 20,
  },
  profileOptionSubtitle: {
    marginTop: 3,
    fontSize: 12,
    lineHeight: 17,
  },
  profileSectionCard: {
    marginTop: 12,
    borderRadius: 22,
    paddingHorizontal: 15,
    paddingVertical: 13,
    borderWidth: 1,
    overflow: 'hidden',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 7,
  },
  profileCardHeader: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  profileHeaderIconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  profileSectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 22,
  },
  profileSectionSubtitle: {
    marginTop: 3,
    fontSize: 12,
    lineHeight: 17,
  },
  profileInputRow: {
    minHeight: 45,
    borderTopWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  profileInputLabel: {
    fontSize: 14,
    fontWeight: '700',
  },
  profileInputValueRow: {
    minWidth: 118,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  profileInput: {
    minWidth: 54,
    height: 38,
    paddingHorizontal: 0,
    fontSize: 17,
    fontWeight: '800',
    textAlign: 'right',
  },
  profileInputSuffix: {
    marginLeft: 5,
    fontSize: 13,
    fontWeight: '700',
  },
  profileMiniChipRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
  },
  profileFieldCaption: {
    marginTop: 10,
    marginBottom: 7,
    fontSize: 13,
    fontWeight: '800',
  },
  profileChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  profileDayChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
  },
  profileChip: {
    minHeight: 31,
    borderRadius: 15,
    paddingHorizontal: 10,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileChipActive: {
    shadowColor: accent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 5,
  },
  profileChipText: {
    fontSize: 12,
    fontWeight: '800',
  },
  profileActivitiesInput: {
    minHeight: 38,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 13,
    fontSize: 14,
    fontWeight: '700',
  },
  profileTargetSummary: {
    marginTop: 12,
    borderRadius: 18,
    borderWidth: 1,
    padding: 13,
  },
  profileTargetSummaryTitle: {
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 17,
  },
  profileTargetSummaryGrid: {
    marginTop: 8,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  profileTargetSummaryText: {
    minWidth: '46%',
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
  },
  profileTargetSummaryValue: {
    fontWeight: '900',
  },
  activityModalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    paddingHorizontal: 18,
    paddingBottom: 82,
  },
  mealSheet: {
    width: '100%',
    maxWidth: 430,
    alignSelf: 'center',
    borderRadius: 30,
    paddingHorizontal: 18,
    paddingTop: 15,
    paddingBottom: 18,
    borderWidth: 1,
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.3,
    shadowRadius: 32,
    elevation: 18,
  },
  mealSheetHeader: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  mealInputCard: {
    marginTop: 14,
    borderRadius: 22,
    paddingHorizontal: 15,
    paddingTop: 14,
    paddingBottom: 14,
    borderWidth: 1,
  },
  mealNameInput: {
    height: 38,
    borderBottomWidth: 1,
    fontSize: 21,
    fontWeight: '600',
    paddingVertical: 0,
  },
  mealFieldGrid: {
    marginTop: 14,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  mealField: {
    width: '47.5%',
  },
  mealFieldLabel: {
    marginBottom: 6,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  mealNumberInput: {
    height: 38,
    borderRadius: 14,
    paddingHorizontal: 12,
    fontSize: 16,
    fontWeight: '700',
  },
  mealMetaCard: {
    marginTop: 10,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    gap: 12,
  },
  mealMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  mealDateControls: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
  mealTodayChip: {
    minHeight: 34,
    minWidth: 130,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  mealTimeInput: {
    width: 112,
    height: 38,
    borderRadius: 15,
    paddingHorizontal: 13,
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '700',
  },
  scannerSoonButton: {
    marginTop: 10,
    minHeight: 40,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  scannerSoonText: {
    fontSize: 13,
    fontWeight: '700',
  },
  mealDeleteButton: {
    marginTop: 12,
  },
  scannerPlaceholderCard: {
    width: '100%',
    maxWidth: 360,
    borderRadius: 28,
    padding: 18,
    borderWidth: 1,
    alignItems: 'center',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.24,
    shadowRadius: 28,
    elevation: 18,
  },
  scannerPlaceholderIcon: {
    width: 74,
    height: 74,
    borderRadius: 37,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: accent,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.24,
    shadowRadius: 18,
    elevation: 7,
  },
  scannerPlaceholderTitle: {
    marginTop: 18,
    fontSize: 22,
    fontWeight: '700',
    lineHeight: 28,
  },
  scannerPlaceholderText: {
    marginTop: 8,
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'center',
  },
  scannerCameraFrame: {
    width: '100%',
    height: 240,
    borderRadius: 24,
    overflow: 'hidden',
    backgroundColor: '#111111',
  },
  scannerCamera: {
    flex: 1,
  },
  scannerGuideFrame: {
    position: 'absolute',
    left: 42,
    right: 42,
    top: 72,
    bottom: 72,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: accent,
    backgroundColor: 'transparent',
  },
  scannerBarcodeText: {
    width: '100%',
    marginTop: 12,
    fontSize: 12,
    lineHeight: 16,
    textAlign: 'center',
  },
  scannerStatusPanel: {
    width: '100%',
    height: 240,
    borderRadius: 24,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  scannerStatusIcon: {
    width: 54,
    height: 54,
    borderRadius: 27,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scannerStatusTitle: {
    marginTop: 14,
    fontSize: 19,
    lineHeight: 24,
    fontWeight: '800',
    textAlign: 'center',
  },
  scannerStatusMessage: {
    maxWidth: 250,
    marginTop: 7,
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'center',
  },
  scannerResultCard: {
    width: '100%',
    marginTop: 12,
    borderRadius: 22,
    padding: 14,
  },
  scannerProductHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  scannerProductImage: {
    width: 54,
    height: 54,
    borderRadius: 14,
    marginRight: 12,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  scannerProductText: {
    flex: 1,
  },
  scannerProductName: {
    fontSize: 17,
    fontWeight: '800',
    lineHeight: 22,
  },
  scannerProductBrand: {
    marginTop: 3,
    fontSize: 13,
    lineHeight: 18,
  },
  scannerNutritionGrid: {
    marginTop: 13,
    flexDirection: 'row',
    gap: 8,
  },
  scannerNutritionCell: {
    flex: 1,
    minHeight: 58,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scannerNutritionValue: {
    fontSize: 15,
    fontWeight: '800',
    lineHeight: 20,
  },
  scannerNutritionLabel: {
    marginTop: 2,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 13,
    textTransform: 'uppercase',
  },
  scannerActionRow: {
    width: '100%',
    marginTop: 14,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
  },
  scannerPrimaryButton: {
    minHeight: 42,
    paddingHorizontal: 22,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: accent,
  },
  scannerUseProductButton: {
    width: '100%',
    marginTop: 14,
  },
  scannerSecondaryButton: {
    minHeight: 42,
    paddingHorizontal: 20,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scannerSecondaryButtonText: {
    fontSize: 14,
    fontWeight: '800',
  },
  scannerPlaceholderDone: {
    minHeight: 42,
    marginTop: 20,
    paddingHorizontal: 28,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: accent,
  },
  scannerPlaceholderDoneText: {
    color: '#111111',
    fontSize: 14,
    fontWeight: '800',
  },
  activitySheet: {
    width: '100%',
    maxWidth: 430,
    alignSelf: 'center',
    borderRadius: 28,
    paddingHorizontal: 16,
    paddingTop: 15,
    paddingBottom: 16,
    borderWidth: 1,
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.3,
    shadowRadius: 32,
    elevation: 22,
  },
  sheetHandle: {
    width: 46,
    height: 4,
    alignSelf: 'center',
    borderRadius: 3,
    opacity: 0.8,
  },
  sheetHeader: {
    height: 52,
    marginTop: 9,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sheetRoundButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetSaveButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: accent,
  },
  sheetTitle: {
    position: 'absolute',
    left: 62,
    right: 62,
    textAlign: 'center',
    fontSize: 24,
    fontWeight: '800',
    lineHeight: 30,
  },
  activityInputCard: {
    minHeight: 108,
    marginTop: 9,
    borderRadius: 22,
    paddingHorizontal: 15,
    paddingTop: 15,
    paddingBottom: 12,
    borderWidth: 1,
  },
  activityTitleInput: {
    height: 36,
    borderBottomWidth: 1,
    fontSize: 21,
    fontWeight: '500',
    paddingVertical: 0,
  },
  activityDescriptionInput: {
    minHeight: 44,
    marginTop: 11,
    fontSize: 17,
    lineHeight: 22,
    padding: 0,
    textAlignVertical: 'top',
  },
  activityFormCard: {
    marginTop: 12,
    borderRadius: 22,
    paddingHorizontal: 15,
    borderWidth: 1,
  },
  activityFormRow: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  formDivider: {
    borderTopWidth: 1,
  },
  formRowLabel: {
    fontSize: 18,
    fontWeight: '500',
    lineHeight: 23,
  },
  allDaySwitch: {
    width: 58,
    height: 30,
    borderRadius: 15,
    padding: 3,
  },
  allDayKnob: {
    width: 24,
    height: 24,
    borderRadius: 12,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 5,
    elevation: 4,
  },
  formChips: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  formChip: {
    minWidth: 78,
    height: 35,
    paddingHorizontal: 11,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  formChipActive: {
    shadowColor: accent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.22,
    shadowRadius: 8,
    elevation: 5,
  },
  formChipText: {
    color: accent,
    fontSize: 14,
    fontWeight: '600',
  },
  formChipTextActive: {
    color: '#111111',
  },
  timeEditor: {
    paddingVertical: 8,
    borderTopWidth: 1,
  },
  dateSelector: {
    minHeight: 50,
    paddingVertical: 8,
    borderTopWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  dateStepButton: {
    width: 34,
    height: 34,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dateSelectorLabel: {
    flex: 1,
    height: 34,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  dateSelectorText: {
    fontSize: 14,
    fontWeight: '800',
  },
  dateTodayButton: {
    height: 34,
    paddingHorizontal: 11,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: accent,
  },
  dateTodayText: {
    color: '#111111',
    fontSize: 13,
    fontWeight: '900',
  },
  timeEditorLabel: {
    marginBottom: 6,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  timeFieldRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
  },
  timeUnitBlock: {
    alignItems: 'center',
    gap: 4,
  },
  timeNudgeButton: {
    width: 36,
    height: 25,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timeNumberInput: {
    width: 48,
    height: 34,
    borderRadius: 13,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '800',
    paddingVertical: 0,
  },
  timeUnitLabel: {
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  timeColon: {
    marginTop: -15,
    fontSize: 24,
    fontWeight: '800',
  },
  colorOptions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 6,
  },
  colorSelectorWrap: {
    maxWidth: 188,
    alignItems: 'center',
  },
  colorButton: {
    width: 27,
    height: 27,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  colorDot: {
    width: 19,
    height: 19,
    borderRadius: 10,
  },
  colorCheckBadge: {
    position: 'absolute',
    width: 15,
    height: 15,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.92)',
  },
  customColorCircle: {
    width: 19,
    height: 19,
    borderRadius: 10,
    overflow: 'hidden',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  customColorPart: {
    width: '50%',
    height: '50%',
  },
  customColorPartOne: {
    backgroundColor: '#ff4f8b',
  },
  customColorPartTwo: {
    backgroundColor: '#2f7df6',
  },
  customColorPartThree: {
    backgroundColor: '#b8ef2f',
  },
  customColorPartFour: {
    backgroundColor: '#ffa43b',
  },
  expandedColorPalette: {
    width: 122,
    marginTop: 8,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignSelf: 'center',
    gap: 6,
  },
  paletteColorButton: {
    width: 26,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  paletteColorDot: {
    width: 18,
    height: 18,
    borderRadius: 9,
  },
  repeatCard: {
    marginTop: 12,
    borderRadius: 21,
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderWidth: 1,
  },
  repeatHeaderRow: {
    minHeight: 31,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  repeatValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  repeatValue: {
    color: accent,
    fontSize: 17,
    fontWeight: '500',
  },
  repeatOptions: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
  },
  repeatOptionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  repeatOptionButton: {
    minWidth: 70,
    height: 33,
    borderRadius: 14,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  repeatOptionText: {
    fontSize: 13,
    fontWeight: '800',
  },
  weekdayChips: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 5,
  },
  weekdayChip: {
    flex: 1,
    height: 30,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  weekdayChipText: {
    fontSize: 12,
    fontWeight: '900',
  },
  deleteSection: {
    marginTop: 11,
  },
  deleteButton: {
    height: 40,
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  deleteButtonText: {
    color: '#ff5d5d',
    fontSize: 14,
    fontWeight: '800',
  },
  deleteConfirmRow: {
    flexDirection: 'row',
    gap: 10,
  },
  deleteCancelButton: {
    flex: 1,
    height: 40,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteCancelText: {
    fontSize: 14,
    fontWeight: '800',
  },
  deleteConfirmButton: {
    flex: 1.4,
    height: 40,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,93,93,0.16)',
    borderWidth: 1,
    borderColor: 'rgba(255,93,93,0.35)',
  },
  deleteConfirmText: {
    color: '#ff5d5d',
    fontSize: 14,
    fontWeight: '900',
  },
  modalOverlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 26,
  },
  modalCard: {
    width: '100%',
    maxWidth: 360,
    borderRadius: 28,
    padding: 22,
    borderWidth: 1,
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.28,
    shadowRadius: 28,
    elevation: 18,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modalTitle: {
    fontSize: 25,
    fontWeight: '700',
    lineHeight: 31,
  },
  modalCloseButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalValueBox: {
    marginTop: 20,
    minHeight: 86,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalValue: {
    fontSize: 42,
    fontWeight: '700',
    letterSpacing: 0,
  },
  stepSelector: {
    marginTop: 16,
    padding: 4,
    borderRadius: 18,
    flexDirection: 'row',
  },
  stepPill: {
    flex: 1,
    height: 42,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepPillActive: {
    backgroundColor: accent,
  },
  stepText: {
    fontSize: 14,
    fontWeight: '700',
  },
  modalControls: {
    marginTop: 22,
    flexDirection: 'row',
    gap: 14,
  },
  adjustButton: {
    flex: 1,
    height: 62,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  adjustButtonPrimary: {
    flex: 1,
    height: 62,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: accent,
  },
  doneButton: {
    height: 52,
    marginTop: 16,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: accent,
  },
  doneButtonText: {
    color: '#111111',
    fontSize: 16,
    fontWeight: '800',
  },
  tabBar: {
    position: 'absolute',
    left: 28,
    right: 28,
    bottom: 18,
    height: 86,
    borderRadius: 31,
    paddingHorizontal: 18,
    paddingTop: 13,
    flexDirection: 'row',
    justifyContent: 'space-between',
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.18,
    shadowRadius: 22,
    elevation: 18,
  },
  darkTabBar: {},
  lightTabBar: {
    left: 28,
    right: 28,
    bottom: 18,
    height: 86,
    borderRadius: 31,
    borderTopWidth: 1,
    shadowOpacity: 0.08,
    elevation: 8,
  },
  tabBarWithQr: {
    left: 20,
    right: 20,
    paddingHorizontal: 18,
  },
  tabButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    position: 'relative',
  },
  tabButtonBeforeQr: {
    marginRight: TAB_QR_BUTTON_SIZE / 2,
  },
  tabButtonAfterQr: {
    marginLeft: TAB_QR_BUTTON_SIZE / 2,
  },
  tabQrCenterWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: -20,
    alignItems: 'center',
    zIndex: 10,
    elevation: 20,
  },
  tabQrButton: {
    width: TAB_QR_BUTTON_SIZE,
    height: TAB_QR_BUTTON_SIZE,
    borderRadius: 32,
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 24,
    elevation: 20,
    zIndex: 5,
  },
  tabText: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 16,
  },
});
