import { StyleSheet } from 'react-native';
import { accent, carbsColor, fatColor } from '../constants/colors';
import {
  CARD_HEIGHT,
  NUTRITION_DATE_CARD_WIDTH,
  NUTRITION_FIXED_HEADER_HEIGHT,
  TIMELINE_VIEWPORT_HEIGHT,
  TIMELINE_WIDTH,
} from '../constants/layout';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    alignItems: 'center',
  },
  phoneFrame: {
    flex: 1,
    width: '100%',
    maxWidth: 430,
    overflow: 'hidden',
  },
  homeContent: {
    flex: 1,
    paddingHorizontal: 27,
    paddingTop: 68,
    paddingBottom: 122,
  },
  screenHeaderRow: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  screenHeaderActions: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 10,
  },
  homeHeader: {
  },
  homeTitleBlock: {
    flex: 1,
    paddingRight: 12,
  },
  homePageTitle: {
    fontSize: 30,
    fontWeight: '700',
    lineHeight: 38,
    letterSpacing: 0,
    opacity: 0.46,
  },
  homeHeaderActions: {
  },
  themeButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  homeActionButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 7,
  },
  topActionButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: accent,
    shadowColor: accent,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.28,
    shadowRadius: 18,
    elevation: 8,
  },
  topActionNeutralButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activityCards: {
    flex: 1,
    marginTop: 24,
    marginHorizontal: -4,
  },
  activityCardsContent: {
    gap: 10,
    paddingHorizontal: 4,
    paddingBottom: 16,
    justifyContent: 'flex-start',
    flexGrow: 1,
  },
  homeEmptyActivityCard: {
    minHeight: 94,
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingVertical: 16,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  activityTouchable: {
    borderRadius: 24,
  },
  homeActivityCard: {
    minHeight: 100,
    borderRadius: 24,
    paddingLeft: 24,
    paddingRight: 18,
    paddingVertical: 17,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'flex-start',
    overflow: 'hidden',
    shadowOffset: { width: 0, height: 14 },
    shadowRadius: 22,
    elevation: 9,
  },
  activityGlassSheen: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 30,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    opacity: 0.62,
  },
  activityEdgeGlow: {
    position: 'absolute',
    left: 0,
    top: 15,
    bottom: 15,
    width: 13,
    borderTopRightRadius: 14,
    borderBottomRightRadius: 14,
  },
  activityEdgeFade: {
    position: 'absolute',
    left: 0,
    top: 10,
    bottom: 10,
    width: 82,
  },
  activityTextBlock: {
    flex: 1,
    marginLeft: 0,
    paddingRight: 4,
  },
  activityCardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  activityTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 22,
  },
  activityTime: {
    flexShrink: 0,
    maxWidth: 126,
    textAlign: 'right',
    fontSize: 15,
    lineHeight: 20,
  },
  activityDescription: {
    marginTop: 9,
    fontSize: 13,
    lineHeight: 18,
  },
  activityAccent: {
    position: 'absolute',
    left: 0,
    top: 21,
    bottom: 21,
    width: 4,
    borderTopRightRadius: 4,
    borderBottomRightRadius: 4,
    opacity: 0.9,
  },
  statsCard: {
    minHeight: 222,
    marginTop: 18,
    marginBottom: 24,
    borderRadius: 23,
    paddingHorizontal: 20,
    paddingTop: 19,
    paddingBottom: 20,
    borderWidth: 1,
    shadowOffset: { width: 0, height: 18 },
    shadowRadius: 28,
    elevation: 14,
  },
  statsTitle: {
    marginBottom: 19,
    color: accent,
    fontSize: 19,
    fontWeight: '700',
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  statItem: {
    width: '50%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  statLeft: {
    paddingRight: 19,
    borderRightWidth: 1,
  },
  statRight: {
    paddingLeft: 21,
  },
  statTop: {
    marginBottom: 28,
  },
  statIconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statTextWrap: {
    flex: 1,
    marginLeft: 14,
  },
  statLabel: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    lineHeight: 14,
  },
  statValueRow: {
    marginTop: 6,
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  statValue: {
    fontSize: 24,
    fontWeight: '500',
    lineHeight: 29,
  },
  statUnit: {
    marginLeft: 4,
    marginBottom: 3,
    fontSize: 13,
    lineHeight: 17,
  },
  statTrack: {
    height: 4,
    marginTop: 7,
    borderRadius: 4,
    overflow: 'visible',
  },
  statFill: {
    height: '100%',
    borderRadius: 3,
    backgroundColor: accent,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 15,
    elevation: 10,
  },
  calendarContent: {
    flex: 1,
    paddingTop: 68,
    paddingHorizontal: 27,
    paddingBottom: 130,
  },
  calendarTop: {
    position: 'relative',
  },
  monthRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: 194,
    flexShrink: 0,
  },
  monthTitle: {
    width: 110,
    marginHorizontal: 6,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 26,
    letterSpacing: 0,
    opacity: 0.82,
  },
  monthNavButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarActions: {
    marginLeft: 6,
    paddingRight: 52,
    transform: [{ translateX: -2 }],
  },
  calendarFixedAddButton: {
    position: 'absolute',
    top: 0,
    right: -2,
  },
  todayButton: {
    height: 36,
    paddingHorizontal: 12,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  todayButtonText: {
    fontSize: 12,
    fontWeight: '800',
  },
  filterButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  weekHeader: {
    marginTop: 36,
    flexDirection: 'row',
  },
  weekday: {
    flex: 1,
    textAlign: 'center',
    fontSize: 12,
    fontWeight: '700',
  },
  calendarGrid: {
    marginTop: 24,
  },
  weekModeRow: {
    marginTop: 17,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 7,
  },
  weekDayCard: {
    flex: 1,
    height: 70,
    borderRadius: 18,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 5,
  },
  weekDayLabel: {
    fontSize: 10,
    fontWeight: '600',
    lineHeight: 13,
  },
  weekDayNumber: {
    marginTop: 4,
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 22,
  },
  weekDotRow: {
    height: 6,
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
  },
  weekActivityDot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
  },
  weekTimelinePanel: {
    marginTop: 18,
    height: TIMELINE_VIEWPORT_HEIGHT,
    borderRadius: 27,
    borderWidth: 1,
    paddingTop: 16,
    paddingBottom: 10,
    paddingHorizontal: 0,
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.18,
    shadowRadius: 28,
    elevation: 10,
    overflow: 'hidden',
  },
  timelineVerticalScroll: {
    flex: 1,
  },
  timelineVerticalContent: {
    paddingBottom: 18,
  },
  weekAllDaySection: {
    paddingHorizontal: 18,
    gap: 10,
    marginBottom: 10,
  },
  allDayTimelineCard: {
    minHeight: 58,
    borderRadius: 18,
    borderWidth: 1,
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'center',
  },
  allDayTimelineText: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  timelineScroll: {
    width: '100%',
  },
  timelineScrollContent: {
    paddingHorizontal: 16,
    flexGrow: 0,
  },
  timelineContent: {
    position: 'relative',
    flexGrow: 0,
    flexShrink: 0,
  },
  timelineHourRow: {
    height: 32,
    position: 'relative',
  },
  timelineHourMarker: {
    position: 'absolute',
    top: 0,
  },
  timelineHourText: {
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 17,
  },
  timelineGridWrap: {
    marginTop: 6,
    position: 'relative',
    width: TIMELINE_WIDTH,
  },
  timelineGuideLine: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 1,
    borderLeftWidth: 1,
    borderStyle: 'dotted',
    borderLeftColor: 'rgba(148,148,148,0.19)',
  },
  timelineActivityCard: {
    position: 'absolute',
    height: CARD_HEIGHT,
    borderRadius: 18,
    borderWidth: 1,
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'stretch',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 18,
    elevation: 6,
  },
  timelineCardAccent: {
    width: 4,
    borderTopRightRadius: 5,
    borderBottomRightRadius: 5,
  },
  timelineCardText: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  timelineCardTitle: {
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 18,
  },
  timelineCardMeta: {
    marginTop: 3,
    fontSize: 11,
    lineHeight: 15,
  },
  weekEmptyState: {
    minHeight: 440,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  weekZoomResetButton: {
    position: 'absolute',
    right: 16,
    bottom: 16,
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  weekEmptyText: {
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'center',
  },
  calendarWeek: {
    height: 64,
    flexDirection: 'row',
  },
  dayCell: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  datePill: {
    width: 45,
    height: 43,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dateActivityDot: {
    position: 'absolute',
    bottom: 5,
    width: 5,
    height: 5,
    borderRadius: 2.5,
  },
  datePillSelected: {
    backgroundColor: accent,
  },
  todayDatePill: {
    borderWidth: 1,
    borderColor: 'rgba(184,239,47,0.58)',
    backgroundColor: 'rgba(184,239,47,0.07)',
  },
  dateText: {
    fontSize: 17,
    fontWeight: '500',
  },
  selectedDate: {
    color: '#101010',
    fontWeight: '700',
  },
  weekendDate: {
    color: '#c66f6f',
  },
  eventsPanel: {
    marginHorizontal: -28,
    marginTop: 5,
    borderTopWidth: 1,
    flex: 1,
  },
  eventsPanelContent: {
    paddingHorizontal: 28,
    paddingTop: 25,
    paddingBottom: 138,
  },
  todayTitle: {
    marginBottom: 18,
    color: '#8bd314',
    fontSize: 17,
    fontWeight: '600',
  },
  eventRow: {
    minHeight: 74,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  eventDot: {
    width: 10,
    height: 10,
    marginTop: 11,
    borderRadius: 5,
  },
  eventTime: {
    width: 104,
    marginLeft: 18,
    fontSize: 16,
    lineHeight: 30,
  },
  eventDetails: {
    flex: 1,
    minHeight: 56,
    paddingBottom: 16,
  },
  eventDivider: {
    borderBottomWidth: 1,
  },
  eventTitle: {
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 23,
  },
  eventMeta: {
    fontSize: 15,
    lineHeight: 20,
  },
  emptyActivitiesText: {
    fontSize: 16,
    lineHeight: 22,
  },
  emptyAgendaCard: {
    minHeight: 78,
    borderRadius: 22,
    paddingHorizontal: 18,
    paddingVertical: 16,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  emptyAgendaIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyAgendaTextBlock: {
    flex: 1,
    marginLeft: 14,
  },
  emptyAgendaTitle: {
    fontSize: 17,
    fontWeight: '700',
    lineHeight: 22,
  },
  nutritionContent: {
    flex: 1,
  },
  nutritionFixedHeader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 20,
    elevation: 20,
    paddingHorizontal: 27,
    paddingTop: 68,
    paddingBottom: 34,
  },
  nutritionBodyScroll: {
    flex: 1,
  },
  nutritionBodyContent: {
    paddingHorizontal: 27,
    paddingTop: NUTRITION_FIXED_HEADER_HEIGHT,
    paddingBottom: 172,
  },
  nutritionHeader: {
  },
  nutritionTitle: {
    flex: 1,
    fontSize: 32,
    fontWeight: '700',
    lineHeight: 40,
    opacity: 0.84,
  },
  nutritionHeaderActions: {
  },
  nutritionDateHeader: {
    marginTop: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  nutritionMonthLabel: {
    width: 132,
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 25,
    opacity: 0.76,
  },
  streakPill: {
    height: 40,
    paddingHorizontal: 13,
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 6,
  },
  streakText: {
    fontSize: 13,
    fontWeight: '600',
    opacity: 0.78,
  },
  nutritionWeekRow: {
    paddingHorizontal: 1,
    paddingRight: 24,
    paddingVertical: 6,
    flexDirection: 'row',
    gap: 7,
  },
  nutritionDateScrollerFrame: {
    height: 88,
    marginTop: 14,
    marginHorizontal: -1,
    marginBottom: 20,
    overflow: 'visible',
  },
  nutritionWeekScroll: {
    height: 88,
    flexGrow: 0,
    overflow: 'visible',
  },
  nutritionDateCard: {
    width: NUTRITION_DATE_CARD_WIDTH,
    height: 70,
    flexGrow: 0,
    flexShrink: 0,
    borderRadius: 18,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 5,
  },
  caloriesCard: {
    minHeight: 150,
    marginTop: 0,
    borderRadius: 28,
    paddingHorizontal: 26,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.1,
    shadowRadius: 24,
    elevation: 12,
  },
  caloriesLeftNumber: {
    fontSize: 46,
    fontWeight: '700',
    lineHeight: 54,
    opacity: 0.86,
  },
  caloriesLeftLabel: {
    marginTop: 4,
    fontSize: 17,
    lineHeight: 22,
    opacity: 0.82,
  },
  nutritionRing: {
    borderWidth: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  nutritionRingArc: {
    position: 'absolute',
    borderWidth: 12,
    borderLeftColor: 'transparent',
    borderBottomColor: 'transparent',
  },
  nutritionRingCenter: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  fatGlyph: {
    position: 'relative',
  },
  fatBubble: {
    position: 'absolute',
    opacity: 0.92,
    shadowColor: fatColor,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.22,
    shadowRadius: 6,
  },
  carbsGlyph: {
    position: 'relative',
    alignItems: 'center',
  },
  carbsStem: {
    position: 'absolute',
    top: '12%',
    bottom: '8%',
    width: 2,
    borderRadius: 2,
  },
  grainLeft: {
    position: 'absolute',
    left: '16%',
    width: '34%',
    height: '20%',
    borderTopLeftRadius: 12,
    borderBottomRightRadius: 12,
    transform: [{ rotate: '-32deg' }],
    shadowColor: carbsColor,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 5,
  },
  grainRight: {
    position: 'absolute',
    right: '16%',
    width: '34%',
    height: '20%',
    borderTopRightRadius: 12,
    borderBottomLeftRadius: 12,
    transform: [{ rotate: '32deg' }],
    shadowColor: carbsColor,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 5,
  },
  macroGrid: {
    marginTop: 20,
    flexDirection: 'row',
    gap: 11,
  },
  macroCard: {
    flex: 1,
    minHeight: 148,
    borderRadius: 24,
    padding: 15,
    borderWidth: 1,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 8,
  },
  macroValue: {
    fontSize: 24,
    fontWeight: '700',
    lineHeight: 30,
    opacity: 0.86,
  },
  macroLabel: {
    marginTop: 4,
    marginBottom: 12,
    fontSize: 13,
    lineHeight: 17,
    opacity: 0.82,
  },
  nutritionCarouselDots: {
    marginTop: 8,
    flexDirection: 'row',
    alignSelf: 'center',
    gap: 9,
  },
  nutritionCarouselDot: {
    width: 9,
    height: 9,
    borderRadius: 4.5,
  },
  recentTitle: {
    marginTop: 15,
    marginBottom: 9,
    fontSize: 21,
    fontWeight: '700',
    lineHeight: 28,
    opacity: 0.9,
  },
  mealCard: {
    minHeight: 118,
    borderRadius: 25,
    borderWidth: 1,
    padding: 17,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.09,
    shadowRadius: 20,
    elevation: 10,
  },
  mealCardStack: {
    marginTop: 9,
  },
  mealCardBody: {
    flex: 1,
  },
  mealCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  mealName: {
    flex: 1,
    fontSize: 17,
    fontWeight: '700',
    lineHeight: 22,
    opacity: 0.9,
  },
  mealTimePill: {
    minHeight: 30,
    paddingHorizontal: 10,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mealTimeText: {
    fontSize: 11,
    fontWeight: '600',
  },
  mealCaloriesRow: {
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  mealCaloriesText: {
    fontSize: 16,
    fontWeight: '700',
    opacity: 0.9,
  },
  mealMacrosRow: {
    marginTop: 15,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  mealMacroText: {
    fontSize: 13,
    fontWeight: '600',
  },
  mealMacroDivider: {
    width: 1,
    height: 18,
    marginHorizontal: 3,
  },
  nutritionEmptyCard: {
    minHeight: 92,
    borderRadius: 24,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  nutritionEmptyText: {
    fontSize: 15,
    fontWeight: '600',
  },
  profileContent: {
    flex: 1,
    paddingHorizontal: 27,
    paddingTop: 68,
    paddingBottom: 120,
  },
  profileHeader: {
  },
  profileTitle: {
    fontSize: 38,
    fontWeight: '800',
    lineHeight: 46,
  },
  profileAvatar: {
  },
  profileCard: {
    marginTop: 28,
    borderRadius: 27,
    padding: 22,
    borderWidth: 1,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 8,
  },
  profileName: {
    fontSize: 25,
    fontWeight: '800',
    lineHeight: 32,
  },
  profileMeta: {
    marginTop: 6,
    fontSize: 15,
    lineHeight: 21,
  },
  settingCard: {
    minHeight: 86,
    marginTop: 18,
    borderRadius: 25,
    paddingHorizontal: 20,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 7,
  },
  settingLabel: {
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 24,
  },
  settingHint: {
    marginTop: 4,
    fontSize: 14,
    lineHeight: 20,
  },
  activityModalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    paddingHorizontal: 18,
    paddingBottom: 82,
  },
  mealSheet: {
    width: '100%',
    maxWidth: 430,
    alignSelf: 'center',
    borderRadius: 30,
    paddingHorizontal: 18,
    paddingTop: 15,
    paddingBottom: 18,
    borderWidth: 1,
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.3,
    shadowRadius: 32,
    elevation: 18,
  },
  mealSheetHeader: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  mealInputCard: {
    marginTop: 14,
    borderRadius: 22,
    paddingHorizontal: 15,
    paddingTop: 14,
    paddingBottom: 14,
    borderWidth: 1,
  },
  mealNameInput: {
    height: 38,
    borderBottomWidth: 1,
    fontSize: 21,
    fontWeight: '600',
    paddingVertical: 0,
  },
  mealFieldGrid: {
    marginTop: 14,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  mealField: {
    width: '47.5%',
  },
  mealFieldLabel: {
    marginBottom: 6,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  mealNumberInput: {
    height: 38,
    borderRadius: 14,
    paddingHorizontal: 12,
    fontSize: 16,
    fontWeight: '700',
  },
  mealMetaCard: {
    marginTop: 10,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    gap: 12,
  },
  mealMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  mealDateControls: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
  mealTodayChip: {
    minHeight: 34,
    minWidth: 130,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  mealTimeInput: {
    width: 112,
    height: 38,
    borderRadius: 15,
    paddingHorizontal: 13,
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '700',
  },
  scannerSoonButton: {
    marginTop: 10,
    minHeight: 40,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  scannerSoonText: {
    fontSize: 13,
    fontWeight: '700',
  },
  mealDeleteButton: {
    marginTop: 12,
  },
  scannerPlaceholderCard: {
    width: '100%',
    maxWidth: 330,
    borderRadius: 28,
    padding: 24,
    borderWidth: 1,
    alignItems: 'center',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.24,
    shadowRadius: 28,
    elevation: 18,
  },
  scannerPlaceholderIcon: {
    width: 74,
    height: 74,
    borderRadius: 37,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: accent,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.24,
    shadowRadius: 18,
    elevation: 7,
  },
  scannerPlaceholderTitle: {
    marginTop: 18,
    fontSize: 22,
    fontWeight: '700',
    lineHeight: 28,
  },
  scannerPlaceholderText: {
    marginTop: 8,
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'center',
  },
  scannerPlaceholderDone: {
    minHeight: 42,
    marginTop: 20,
    paddingHorizontal: 28,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: accent,
  },
  scannerPlaceholderDoneText: {
    color: '#111111',
    fontSize: 14,
    fontWeight: '800',
  },
  activitySheet: {
    width: '100%',
    maxWidth: 430,
    alignSelf: 'center',
    borderRadius: 28,
    paddingHorizontal: 16,
    paddingTop: 15,
    paddingBottom: 16,
    borderWidth: 1,
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.3,
    shadowRadius: 32,
    elevation: 22,
  },
  sheetHandle: {
    width: 46,
    height: 4,
    alignSelf: 'center',
    borderRadius: 3,
    opacity: 0.8,
  },
  sheetHeader: {
    height: 52,
    marginTop: 9,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sheetRoundButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetSaveButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: accent,
  },
  sheetTitle: {
    position: 'absolute',
    left: 62,
    right: 62,
    textAlign: 'center',
    fontSize: 24,
    fontWeight: '800',
    lineHeight: 30,
  },
  activityInputCard: {
    minHeight: 108,
    marginTop: 9,
    borderRadius: 22,
    paddingHorizontal: 15,
    paddingTop: 15,
    paddingBottom: 12,
    borderWidth: 1,
  },
  activityTitleInput: {
    height: 36,
    borderBottomWidth: 1,
    fontSize: 21,
    fontWeight: '500',
    paddingVertical: 0,
  },
  activityDescriptionInput: {
    minHeight: 44,
    marginTop: 11,
    fontSize: 17,
    lineHeight: 22,
    padding: 0,
    textAlignVertical: 'top',
  },
  activityFormCard: {
    marginTop: 12,
    borderRadius: 22,
    paddingHorizontal: 15,
    borderWidth: 1,
  },
  activityFormRow: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  formDivider: {
    borderTopWidth: 1,
  },
  formRowLabel: {
    fontSize: 18,
    fontWeight: '500',
    lineHeight: 23,
  },
  allDaySwitch: {
    width: 58,
    height: 30,
    borderRadius: 15,
    padding: 3,
  },
  allDayKnob: {
    width: 24,
    height: 24,
    borderRadius: 12,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 5,
    elevation: 4,
  },
  formChips: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  formChip: {
    minWidth: 78,
    height: 35,
    paddingHorizontal: 11,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  formChipActive: {
    shadowColor: accent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.22,
    shadowRadius: 8,
    elevation: 5,
  },
  formChipText: {
    color: accent,
    fontSize: 14,
    fontWeight: '600',
  },
  formChipTextActive: {
    color: '#111111',
  },
  timeEditor: {
    paddingVertical: 8,
    borderTopWidth: 1,
  },
  dateSelector: {
    minHeight: 50,
    paddingVertical: 8,
    borderTopWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  dateStepButton: {
    width: 34,
    height: 34,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dateSelectorLabel: {
    flex: 1,
    height: 34,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  dateSelectorText: {
    fontSize: 14,
    fontWeight: '800',
  },
  dateTodayButton: {
    height: 34,
    paddingHorizontal: 11,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: accent,
  },
  dateTodayText: {
    color: '#111111',
    fontSize: 13,
    fontWeight: '900',
  },
  timeEditorLabel: {
    marginBottom: 6,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  timeFieldRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
  },
  timeUnitBlock: {
    alignItems: 'center',
    gap: 4,
  },
  timeNudgeButton: {
    width: 36,
    height: 25,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timeNumberInput: {
    width: 48,
    height: 34,
    borderRadius: 13,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '800',
    paddingVertical: 0,
  },
  timeUnitLabel: {
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  timeColon: {
    marginTop: -15,
    fontSize: 24,
    fontWeight: '800',
  },
  colorOptions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 6,
  },
  colorSelectorWrap: {
    maxWidth: 188,
    alignItems: 'center',
  },
  colorButton: {
    width: 27,
    height: 27,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  colorDot: {
    width: 19,
    height: 19,
    borderRadius: 10,
  },
  colorCheckBadge: {
    position: 'absolute',
    width: 15,
    height: 15,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.92)',
  },
  customColorCircle: {
    width: 19,
    height: 19,
    borderRadius: 10,
    overflow: 'hidden',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  customColorPart: {
    width: '50%',
    height: '50%',
  },
  customColorPartOne: {
    backgroundColor: '#ff4f8b',
  },
  customColorPartTwo: {
    backgroundColor: '#2f7df6',
  },
  customColorPartThree: {
    backgroundColor: '#b8ef2f',
  },
  customColorPartFour: {
    backgroundColor: '#ffa43b',
  },
  expandedColorPalette: {
    width: 122,
    marginTop: 8,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignSelf: 'center',
    gap: 6,
  },
  paletteColorButton: {
    width: 26,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  paletteColorDot: {
    width: 18,
    height: 18,
    borderRadius: 9,
  },
  repeatCard: {
    marginTop: 12,
    borderRadius: 21,
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderWidth: 1,
  },
  repeatHeaderRow: {
    minHeight: 31,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  repeatValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  repeatValue: {
    color: accent,
    fontSize: 17,
    fontWeight: '500',
  },
  repeatOptions: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
  },
  repeatOptionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  repeatOptionButton: {
    minWidth: 70,
    height: 33,
    borderRadius: 14,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  repeatOptionText: {
    fontSize: 13,
    fontWeight: '800',
  },
  weekdayChips: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 5,
  },
  weekdayChip: {
    flex: 1,
    height: 30,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  weekdayChipText: {
    fontSize: 12,
    fontWeight: '900',
  },
  deleteSection: {
    marginTop: 11,
  },
  deleteButton: {
    height: 40,
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  deleteButtonText: {
    color: '#ff5d5d',
    fontSize: 14,
    fontWeight: '800',
  },
  deleteConfirmRow: {
    flexDirection: 'row',
    gap: 10,
  },
  deleteCancelButton: {
    flex: 1,
    height: 40,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteCancelText: {
    fontSize: 14,
    fontWeight: '800',
  },
  deleteConfirmButton: {
    flex: 1.4,
    height: 40,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,93,93,0.16)',
    borderWidth: 1,
    borderColor: 'rgba(255,93,93,0.35)',
  },
  deleteConfirmText: {
    color: '#ff5d5d',
    fontSize: 14,
    fontWeight: '900',
  },
  modalOverlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 26,
  },
  modalCard: {
    width: '100%',
    maxWidth: 360,
    borderRadius: 28,
    padding: 22,
    borderWidth: 1,
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.28,
    shadowRadius: 28,
    elevation: 18,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modalTitle: {
    fontSize: 25,
    fontWeight: '700',
    lineHeight: 31,
  },
  modalCloseButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalValueBox: {
    marginTop: 20,
    minHeight: 86,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalValue: {
    fontSize: 42,
    fontWeight: '700',
    letterSpacing: 0,
  },
  stepSelector: {
    marginTop: 16,
    padding: 4,
    borderRadius: 18,
    flexDirection: 'row',
  },
  stepPill: {
    flex: 1,
    height: 42,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepPillActive: {
    backgroundColor: accent,
  },
  stepText: {
    fontSize: 14,
    fontWeight: '700',
  },
  modalControls: {
    marginTop: 22,
    flexDirection: 'row',
    gap: 14,
  },
  adjustButton: {
    flex: 1,
    height: 62,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  adjustButtonPrimary: {
    flex: 1,
    height: 62,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: accent,
  },
  doneButton: {
    height: 52,
    marginTop: 16,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: accent,
  },
  doneButtonText: {
    color: '#111111',
    fontSize: 16,
    fontWeight: '800',
  },
  tabBar: {
    position: 'absolute',
    left: 28,
    right: 28,
    bottom: 18,
    height: 86,
    borderRadius: 31,
    paddingHorizontal: 18,
    paddingTop: 13,
    flexDirection: 'row',
    justifyContent: 'space-between',
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.18,
    shadowRadius: 22,
    elevation: 18,
  },
  darkTabBar: {},
  lightTabBar: {
    left: 28,
    right: 28,
    bottom: 18,
    height: 86,
    borderRadius: 31,
    borderTopWidth: 1,
    shadowOpacity: 0.08,
    elevation: 8,
  },
  tabBarWithQr: {
    left: 20,
    right: 20,
    paddingHorizontal: 14,
  },
  tabButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    position: 'relative',
  },
  tabButtonBeforeQr: {
    marginRight: 24,
  },
  tabButtonAfterQr: {
    marginLeft: 24,
  },
  tabQrButton: {
    position: 'absolute',
    left: '50%',
    top: -20,
    width: 64,
    height: 64,
    marginLeft: -32,
    borderRadius: 32,
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 24,
    elevation: 20,
    zIndex: 5,
  },
  tabText: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 16,
  },
  homeIndicator: {
    position: 'absolute',
    bottom: 8,
    left: '50%',
    width: 118,
    height: 5,
    marginLeft: -59,
    borderRadius: 3,
  },
});
